# Generated by Django 2.0 on 2018-09-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_kpi_tbcell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbcell',
            name='ELECTTILT',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbcell',
            name='HEIGHT',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbcell',
            name='MECHTILT',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbcell',
            name='TOTLETILT',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
