# Generated by Django 2.0 on 2018-09-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0003_auto_20180906_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='SECTOR_DETAIL',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='DIF_RATE',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='SECTOR_NAME',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='eNodeB_IN_RATE',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
