# Generated by Django 2.0 on 2018-09-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0004_auto_20180906_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='START_TIME',
            field=models.CharField(max_length=50),
        ),
    ]
