# Generated by Django 2.0 on 2018-09-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0006_auto_20180906_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='DOWN_BIT',
            field=models.BigIntegerField(),
        ),
    ]
