# Generated by Django 2.0 on 2018-09-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0007_auto_20180906_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='UP_BIT',
            field=models.BigIntegerField(),
        ),
    ]
