# Generated by Django 2.0 on 2018-09-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0009_auto_20180906_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='eNodeB_OUT_RATE',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
