# Generated by Django 2.0 on 2018-09-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0010_auto_20180906_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='SECTOR_DETAIL',
            field=models.TextField(max_length=100),
        ),
    ]
