# Generated by Django 2.0 on 2018-09-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0012_prb'),
    ]

    operations = [
        migrations.CreateModel(
            name='MRO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.CharField(max_length=50)),
                ('ServingSector', models.CharField(max_length=50)),
                ('InterferingSector', models.CharField(max_length=50)),
                ('LteScRSRP', models.IntegerField()),
                ('LteNcRSRP', models.IntegerField()),
                ('LteNcEarfcn', models.IntegerField()),
                ('LteNcPci', models.IntegerField()),
            ],
        ),
    ]
