# Generated by Django 2.0 on 2018-09-07 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0013_mro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mro',
            old_name='TimeStamp',
            new_name='_TimeStamp',
        ),
    ]
