# Generated by Django 2.0 on 2018-09-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0014_auto_20180908_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbC2Inew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServingSector', models.CharField(max_length=50)),
                ('InterferingSector', models.CharField(max_length=50)),
                ('mean', models.IntegerField()),
                ('standard_deviation', models.IntegerField()),
                ('rate1', models.FloatField()),
                ('rate2', models.FloatField()),
            ],
        ),
    ]
