# Generated by Django 2.0 on 2018-09-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0015_tbc2inew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbc2inew',
            name='mean',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tbc2inew',
            name='standard_deviation',
            field=models.FloatField(),
        ),
    ]
