# Generated by Django 2.0 on 2018-09-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0016_auto_20180911_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='indextb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c2i', models.FloatField()),
            ],
        ),
    ]
