# Generated by Django 2.0 on 2018-09-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0017_indextb'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbC2I3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector1', models.CharField(max_length=50)),
                ('sector2', models.CharField(max_length=50)),
                ('sector3', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='indextb',
        ),
    ]
